"""A1 golden-master tests: reproduce the frozen reference panels exactly.

The fixtures were generated by the OLD repo (`~/Projects/alt_nfp`, frozen
reference) via ``scripts/generate_golden_masters.py`` and live in
``s3://alt-nfp/golden/a1/`` (proprietary provider-derived values — only the
manifest is committed). The data layer here must reproduce every censored
panel value-identically; one horizon is pinned as an expected failure.
See ``plans/3-golden_masters.md``.
"""

import json
import os
from datetime import date
from pathlib import Path

import polars as pl
import pytest
from nfp_ingest.panel import build_panel
from nfp_ingest.payroll import ingest_provider
from nfp_lookups.paths import (
    DATA_DIR,
    VINTAGE_STORE_PATH,
    is_remote,
    storage_options_for,
)
from nfp_lookups.provider_config import ProviderConfig

MANIFEST = json.loads(
    (Path(__file__).parent / "golden" / "a1_manifest.json").read_text()
)
START_YEAR = MANIFEST["provenance"]["start_year"]
END_YEAR = MANIFEST["provenance"]["end_year"]
GOLDEN_URI = os.environ.get("NFP_GOLDEN_URI", "s3://alt-nfp/golden/a1")


def _golden_root():
    """UPath to the golden fixtures, or None when not configured."""
    if not is_remote(VINTAGE_STORE_PATH):
        return None
    from upath import UPath

    endpoint = os.environ.get("AWS_ENDPOINT_URL")
    return UPath(
        GOLDEN_URI,
        key=os.environ.get("AWS_ACCESS_KEY_ID"),
        secret=os.environ.get("AWS_SECRET_ACCESS_KEY"),
        client_kwargs={"endpoint_url": endpoint} if endpoint else {},
    )


def _golden_available() -> bool:
    try:
        root = _golden_root()
        return root is not None and (root / "a1_manifest.json").exists()
    except Exception:  # unreachable endpoint / bad credentials → skip
        return False


pytestmark = [
    pytest.mark.skipif(
        not _golden_available(),
        reason="golden fixtures unavailable (need NFP_STORE_URI env + s3 golden/a1 prefix)",
    ),
    pytest.mark.real_store,  # reads s3://.../golden/a1 + real store; exempt from cred blanking
]


def _read_fixture(fname: str) -> pl.DataFrame:
    return pl.read_parquet(
        str(_golden_root() / fname),
        storage_options=storage_options_for(VINTAGE_STORE_PATH),
    )


_PANELS = {
    n: m for n, m in MANIFEST["fixtures"].items() if m["kind"] == "censored_panel"
}
_PROVIDERS = {
    n: m for n, m in MANIFEST["fixtures"].items() if m["kind"] == "provider_panel"
}


@pytest.mark.parametrize("fname", sorted(_PANELS))
def test_censored_panel_matches_master(fname):
    meta = _PANELS[fname]
    as_of = date.fromisoformat(meta["as_of_ref"])

    fixture = _read_fixture(fname)
    assert fixture.height == meta["rows"], "fixture corrupted in transport"
    assert fixture.columns == meta["columns"]

    panel = build_panel(
        providers=[], start_year=START_YEAR, end_year=END_YEAR, as_of_ref=as_of
    )
    assert panel.columns == fixture.columns
    assert panel.height == fixture.height, (
        f"as_of={as_of}: {panel.height} rows vs master {fixture.height}"
    )
    cols = panel.columns
    assert panel.sort(cols).equals(fixture.sort(cols)), (
        f"as_of={as_of}: values diverge from golden master"
    )


@pytest.mark.parametrize("case", MANIFEST["expected_failures"])
def test_unbuildable_horizon_raises(case):
    """Negative master: shutdown-gapped horizons must fail fast, not build."""
    as_of = date.fromisoformat(case["as_of_ref"])
    with pytest.raises(ValueError, match=case["error_contains"]):
        build_panel(
            providers=[], start_year=START_YEAR, end_year=END_YEAR, as_of_ref=as_of
        )


@pytest.mark.parametrize("fname", sorted(_PROVIDERS))
def test_provider_panel_matches_master(fname):
    meta = _PROVIDERS[fname]
    cfg = ProviderConfig(**meta["provider_config"])
    if not (DATA_DIR / cfg.file).exists():
        pytest.skip(f"provider file {cfg.file} not present under DATA_DIR")

    fixture = _read_fixture(fname)
    assert fixture.height == meta["rows"], "fixture corrupted in transport"

    df = ingest_provider(cfg)
    cols = df.columns
    assert cols == fixture.columns
    assert df.sort(cols).equals(fixture.sort(cols)), (
        f"provider {cfg.name}: values diverge from golden master"
    )
