"""A2 golden-master tests: `build_model_data` must reproduce the reference.

Fixtures were generated by the OLD repo's full two-layer pipeline
(`build_panel(as_of_ref=D)` → `panel_to_model_data(PROVIDERS, as_of=D)`,
with its indicators path corrected to production behavior — see
``plans/4-a2_seams_snapshots.md``) and live in ``s3://alt-nfp/golden/a2/``.
Every array must match NaN-aware-exactly; frames value-identically.

H-3 note: the frozen fixtures (schema v2) contain ``birth_rate``, ``bd_proxy``,
and ``bd_qcew_lagged``.  v3 ``build_model_data`` intentionally omits them
(posterior-neutral: the model never read them).  The comparison below excludes
these three arrays so the reference fixtures remain frozen and unmodified.
"""

import json
import os
from datetime import date
from pathlib import Path

import numpy as np
import polars as pl
import pytest
from nfp_ingest.model_data import build_model_data
from nfp_lookups.paths import (
    DATA_DIR,
    VINTAGE_STORE_PATH,
    is_remote,
    storage_options_for,
)
from nfp_lookups.provider_config import PROVIDERS_DEFAULT

MANIFEST = json.loads(
    (Path(__file__).parent / "golden" / "a2_manifest.json").read_text()
)
START_YEAR = MANIFEST["provenance"]["start_year"]
END_YEAR = MANIFEST["provenance"]["end_year"]
GOLDEN_URI = os.environ.get("NFP_GOLDEN_A2_URI", "s3://alt-nfp/golden/a2")


def _golden_root():
    if not is_remote(VINTAGE_STORE_PATH):
        return None
    from upath import UPath

    endpoint = os.environ.get("AWS_ENDPOINT_URL")
    return UPath(
        GOLDEN_URI,
        key=os.environ.get("AWS_ACCESS_KEY_ID"),
        secret=os.environ.get("AWS_SECRET_ACCESS_KEY"),
        client_kwargs={"endpoint_url": endpoint} if endpoint else {},
    )


def _available() -> bool:
    try:
        root = _golden_root()
        if root is None or not (root / "a2_manifest.json").exists():
            return False
        # provider files + indicator parquets must be present locally
        return (DATA_DIR / "providers/g/g_provider.parquet").exists() and (
            DATA_DIR / "indicators/claims.parquet"
        ).exists()
    except Exception:
        return False


pytestmark = [
    pytest.mark.skipif(
        not _available(),
        reason="A2 golden fixtures unavailable (need store env + s3 golden/a2 + local providers/indicators)",
    ),
    pytest.mark.real_store,  # reads s3://.../golden/a2 + real store; exempt from cred blanking
]


def _arrays_equal(name: str, got: np.ndarray, want: np.ndarray) -> None:
    assert got.shape == want.shape, f"{name}: shape {got.shape} vs {want.shape}"
    if np.issubdtype(want.dtype, np.floating):
        assert np.array_equal(
            np.asarray(got, dtype=want.dtype), want, equal_nan=True
        ), f"{name}: float values diverge"
    else:
        assert np.array_equal(np.asarray(got), np.asarray(want)), (
            f"{name}: values diverge"
        )


@pytest.mark.parametrize("stem", sorted(MANIFEST["fixtures"]))
def test_model_data_matches_master(stem):
    meta = MANIFEST["fixtures"][stem]
    as_of = date.fromisoformat(meta["as_of_ref"])
    root = _golden_root()
    opts = storage_options_for(VINTAGE_STORE_PATH)

    data = build_model_data(
        as_of,
        providers=list(PROVIDERS_DEFAULT),
        start_year=START_YEAR,
        end_year=END_YEAR,
    )

    # Scalars + calendar
    for k, v in meta["scalars"].items():
        assert int(data[k]) == v, f"{k}: {data[k]} vs {v}"
    assert data["dates"][0].isoformat() == meta["dates_first"]
    assert data["dates"][-1].isoformat() == meta["dates_last"]
    assert {str(k): v for k, v in data["ces_vintage_map"].items()} == (
        meta["ces_vintage_map"]
    )

    # Cyclical inventory: present arrays present, None stays None
    for k in meta["cyclical_none"]:
        assert data.get(k) is None, f"{k}: expected None"
    for k in meta["cyclical_present"]:
        assert data.get(k) is not None, f"{k}: expected array, got None"

    # Every fixture array, NaN-aware exact.
    # H-3: fixtures (schema v2) contain birth_rate/bd_proxy/bd_qcew_lagged; v3
    # build_model_data intentionally omits them (posterior-neutral).  Exclude
    # them from comparison — the fixtures remain frozen and unmodified.
    _DROPPED = {"birth_rate", "bd_proxy", "bd_qcew_lagged"}
    with (root / f"model_data_{stem}.npz").open("rb") as f:
        fixture = np.load(f)
        want = {k: fixture[k] for k in fixture.files if k not in _DROPPED}
    assert sorted(want) == [n for n in meta["array_names"] if n not in _DROPPED], (
        "fixture corrupted in transport"
    )

    got: dict = {}
    for k in want:
        if "__" in k:  # per-provider arrays: "<name>__<field>"
            pname, field = k.split("__", 1)
            pp = next(p for p in data["pp_data"] if p["name"] == pname)
            got[k] = np.asarray(pp[field])
        else:
            got[k] = np.asarray(data[k])
    for k in sorted(want):
        _arrays_equal(k, got[k], want[k])

    # Provider inventory
    assert [
        {"name": p["name"], "emp_col": p["emp_col"], "has_births": p["births"] is not None}
        for p in data["pp_data"]
    ] == meta["providers"]

    # Frames: levels and the (layer-2 filtered) panel, value-identical
    levels_fix = pl.read_parquet(str(root / f"levels_{stem}.parquet"), storage_options=opts)
    assert data["levels"].columns == levels_fix.columns
    assert data["levels"].equals(levels_fix), "levels frame diverges"

    panel_fix = pl.read_parquet(str(root / f"panel_{stem}.parquet"), storage_options=opts)
    assert panel_fix.height == meta["panel_rows"], "fixture corrupted in transport"
    cols = data["panel"].columns
    assert cols == panel_fix.columns
    assert data["panel"].sort(cols).equals(panel_fix.sort(cols)), "panel diverges"
